version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    container_name: hubx-movies-app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: hubx-movies-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: hubx-movies-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:

networks:
  app-network:
    driver: bridge
